FROM node:latest

# Add application sources
ADD . $HOME

# Install app dependencies
COPY package*.json /usr/src/app/
RUN npm install

# Copy the application source and build artifacts from the builder image to this one
COPY $HOME $HOME

ENV NODE_ENV production
ENV PORT 3000

EXPOSE 3000

# Run script uses standard ways to run the application
CMD npm run -d start



