apiVersion: apps/v1
kind: Deployment
metadata:
  name: scc-tutorial-deploy-sc-sa
spec:
  selector:
    matchLabels:
      app: scc-tutorial-sc-sa
  template:
    metadata:
      labels:
        app: scc-tutorial-sc-sa
    spec:
      containers:
      - image: ubi8/ubi-minimal
        name: ubi-minimal
        command: ['sh', '-c', 'echo "Hello from user $(id -u)" && sleep infinity']
        securityContext:
          runAsUser: 1234
          runAsGroup: 5678
        volumeMounts:
        - mountPath: /var/opt/app/data
          name: data
      serviceAccountName: scc-tutorial-sa
      securityContext:
        fsGroup: 5555
        supplementalGroups: [5777, 5888]
      volumes:
      - emptyDir: {}
        name: data



kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
  namespace: hello2
  uid: 7749d27a-0647-4af7-9b88-b39b8894d3e8
  resourceVersion: '115930'
  generation: 6
  creationTimestamp: '2023-04-14T10:28:48Z'
  labels:
    app: hello-world
    app.kubernetes.io/component: hello-world
    app.kubernetes.io/instance: hello-world
  annotations:
    deployment.kubernetes.io/revision: '4'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"hello-world:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"hello-world\")].image"}]
    openshift.io/generated-by: OpenShiftNewApp
  managedFields:
    - manager: oc
      operation: Update
      apiVersion: apps/v1
      time: '2023-04-14T10:28:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:openshift.io/generated-by': {}
              'f:labels':
                .: {}
                'f:deployment': {}
            'f:spec':
              'f:containers':
                'k:{"name":"hello-world"}':
                  .: {}
                  'f:imagePullPolicy': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":3000,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-04-14T10:43:54Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"hello-world"}':
                  'f:image': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-04-14T10:52:06Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
      subresource: status
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-04-14T17:07:51Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"hello-world"}':
                  'f:securityContext':
                    .: {}
                    'f:runAsGroup': {}
                    'f:runAsUser': {}
              'f:securityContext':
                'f:fsGroup': {}
                'f:supplementalGroups': {}
              'f:serviceAccount': {}
              'f:serviceAccountName': {}
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: hello-world
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: hello-world
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: hello-world
          image: >-
            image-registry.openshift-image-registry.svc:5000/hello2/hello-world@sha256:eb58003de6619ae7ca0aa3880dc17554bc4a00b2cf7968ec5ed5b1ffa7171a49
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1234
            runAsGroup: 5678
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: developer-sa
      serviceAccount: developer-sa
      securityContext:
        supplementalGroups:
          - 5777
          - 5888
        fsGroup: 5555
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 5
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-04-14T10:30:22Z'
      lastTransitionTime: '2023-04-14T10:30:22Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-04-14T10:44:01Z'
      lastTransitionTime: '2023-04-14T10:28:48Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "hello-world-75656647f4" has successfully progressed.